name = "UpAndComingPorts"
uuid = "63d6a6d4-a10b-42f1-bdac-2303c20b3835"
authors = ["Jake Ireland <jakewilliami@icloud.com>", "Finn Sargisson <sarrgies@gmail.com>"]
version = "1.0.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[compat]
DelimitedFiles = "1"
Downloads = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
